PM: sleep: Drop unused call to log_wakeup_reason
../drivers/base/power/wakeup.c:963:4: error: implicit declaration of function 'log_wakeup_reason' [-Werror,-Wimplicit-function-declaration]
                        log_wakeup_reason(irq_number);
                        ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>